modLoader = "kotlinforforge"
loaderVersion = "[5,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "cobblemongymodyssey"
version = "${version}"
displayName = "Cobblemon Gym Odyssey"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.cobblemongymodyssey]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemongymodyssey]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemongymodyssey]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemongymodyssey]]
modId = "kotlinforforge"
type = "required"
versionRange = "[5.9.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemongymodyssey]]
modId = "cobblemon"
type = "required"
versionRange = "[1.7.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemongymodyssey]]
modId = "cobblefurnies"
type = "required"
versionRange = "[1.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemongymodyssey]]
modId = "chipped"
type = "required"
versionRange = "[4.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemongymodyssey]]
modId = "athena"
type = "required"
versionRange = "[4.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemongymodyssey]]
modId = "resourcefullib"
type = "required"
versionRange = "[3.0.12,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cobblemongymodyssey.mixins.json"


